theme: jekyll-theme-minimal
permalink: pretty
name: Nursery Ratings
url: https://krussll.github.io/nursery/

nav-background: #B40604
nav-font: #fff
jumbotron-background: #ECEEEF
jumbotron-font: #fff

collections:
  nursery:
    permalink: /:collection/:name 
