theme: jekyll-theme-minimal
permalink: pretty
name: nurseryratings.co.uk
url: http://www.nurseryratings.co.uk
google_analytics: UA-86474387-4

collections:
  nursery:
    output: true
    permalink: /:collection/:name 
